controller_list:
  - name: fake_body_controller
    type: $(arg fake_execution_type)
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
  - name: fake_end_effector_controller
    type: $(arg fake_execution_type)
    joints:
      - iiwa_joint_7
initial:  # Define initial robot poses per group
#  - group: body
#    pose: home

  []